# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued
# terms.

proc sum_fibs {limit} {
    set x 1
    set y 1
    set sum 0
    while {$y <= $limit} {
        # increase sum
        if {$y % 2 == 0} {incr sum $y}

        # next fib
        set prev $y
        incr y $x
        set x $prev
    }
    return $sum
}

set result [sum_fibs 4000000]
puts "Result: $result"
