-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:

--      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even-valued terms.

-- Generate the Fibonacci sequence
WITH RECURSIVE cte(x, y) AS (
    VALUES(1, 1)
    UNION ALL
    SELECT y, x+y FROM cte WHERE y < 4000000
)
SELECT
    SUM(x) 'Result'
FROM
    cte
WHERE
    x % 2 = 0;
